### ISSUE TITLE
Expected version ">=8"

### ISSUE THREAD

**Issue by bierik** [jonschlinkert/clone-deep#10]
Why is `clone-deep` depending on node >=8?
In https://github.com/jonschlinkert/clone-deep/commit/04d19f176662beafd9f1c1b81a63ac7696ef3f0a the node version has been pinned to >=8. But what is benefit of this change. What functionality of `clone-deep` needs this particular version?
I'm running a project on node 6.14.1 and I am not able to change the version to 8 there.

**Comment by jonschlinkert** [comment]
we might be able to change it to 6, or maybe 4. I'll look into it.

**Comment by jonschlinkert** [comment]
Done!
