### ISSUE TITLE
Lazy caching incompatible with webpack?

### ISSUE THREAD

**Issue by kintel** [jonschlinkert/clone-deep#3]
It looks like the lazy caching introduced in 0.2.2 is incompatible with webpack's static inclusion of dependencies, and should thus be bumped to a different version to avoid accidentally including it under the ^0.2.0 semver.

**Comment by jonschlinkert** [comment]
Should be fixed now. 

For future reference though, webpack itself isn't broadly adopted standard that qualifies as a factor in the versioning of a node module.  After 3 million downloads of lazy-cache, I've had two issues about it, and both are from webpack users.  It's worth considering that lazy-caching is just like any other language pattern and should be recognized by webpack. Until such time, I'd consider it a bug of webpack's and or browserify's.

**Comment by kintel** [comment]
Thx!
I agree that the problem most likely is a bug in external software. I just don't have any good strategies for safeguarding against such incompatibilities.

**Comment by jonschlinkert** [comment]
no problem, thanks for reporting!

**Comment by doowb** [comment]
@kintel you can use [unlazy loader](https://www.npmjs.com/package/unlazy-loader) in your webpack build if you're using libraries that use `lazy-cache`.
